[tool.poetry]
name = "pycount-madddy"
version = "0.1.0"
description = "hii"
authors = ["maddy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
